name: Documentation request
description: Raise an issue related to content.
title: "📝 Doc: "
labels: ["documentation", "to sort"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to improve Tracim's app!
        Before you submit, please make sure the documentation change hasn't already been suggested by searching [open](https://github.com/tracim/mobile_app/issues) and [closed](https://github.com/tracim/mobile_app/issues?q=is%3Aissue+is%3Aclosed).
  - type: input
    id: contents
    attributes:
      label: What file on github.com/tracim/mobile_app is affected?
      placeholder: "github.com/tracim/mobile_app/blob/main/README.md"
    validations:
      required: true
  - type: textarea
    id: why-changes
    attributes:
      label: What part(s) of the content would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see.
        - Why should the docs be changed? What use cases does it support?
        - What is the expected outcome?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context or screenshots about the feature request here"
    validations:
      required: false
  - type: textarea
    id: related-pr
    attributes:
      label: Related PR
      description: |
        Let us know if this is related to an open pull request.
        Leave empty if there is no related PR or if you don't know.
      placeholder: PR #0000
    validations:
      required: false
