name: Feature request
description: Suggest a new feature
title: "✨ Feat: "
labels: ["to sort", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to improve Tracim's app!
        Before you submit, please make sure the feature hasn't already been suggested by searching [open](https://github.com/tracim/mobile_app/issues) and [closed](https://github.com/tracim/mobile_app/issues?q=is%3Aissue+is%3Aclosed).
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: |
        Describe your feature/enhancement and why do you need it in Tracim's app. Preferably use User Story Template to write your need.
      placeholder: >
        As I user, I would like a help page on the app.
        This would help me to know where to find the information I need.
    validations:
      required: true
  - type: textarea
    id: how-it-works
    attributes:
      label: How it works
      description: |
        Describe how your feature works.
      placeholder: |
        When the user types a search query, the popup shows a list of contents that match the query.
        When the user selects a content, the popup closes and the user is redirected to the content.
    validations:
      required: false
  - type: textarea
    id: related-pr
    attributes:
      label: Related PR
      description: |
        Let us know if this is related to an open pull request.
        Leave empty if there is no related PR or if you don't know.
      placeholder: PR #0000
    validations:
      required: false
